# Offset characters' unicodes
# Never edit this unless you know what you are doing
offset-characters:
  font: customcrops:offset_chars
  '1': 
  '2': 
  '4': 
  '8': 
  '16': 
  '32': 
  '64': 
  '128': 
  '-1': 
  '-2': 
  '-4': 
  '-8': 
  '-16': 
  '-32': 
  '-64': 
  '-128': 